# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmePvMFsY6AOCmYYnWtx1FaP8lL-9YmC
"""

import pandas as pd
import requests
from datetime import datetime

# =========================
# 1. CONFIGURACIÓN
# =========================
URL = "https://opendata-ajuntament.barcelona.cat/data/dataset/your-dataset.csv"
OUTPUT_FILE = "data_cleaned.csv"

# =========================
# 2. DESCARGA DE DATOS
# =========================
def download_data(url):
    print("Descargando datos...")
    response = requests.get(url)

    if response.status_code == 200:
        with open("raw_data.csv", "wb") as f:
            f.write(response.content)
        print("Descarga completada")
    else:
        raise Exception("Error al descargar datos")

# =========================
# 3. LIMPIEZA DE DATOS
# =========================
def clean_data():
    print("Limpiando datos...")
    df = pd.read_csv("raw_data.csv")

    # eliminar duplicados
    df = df.drop_duplicates()

    # eliminar nulos
    df = df.dropna()

    # ejemplo: convertir fechas
    if 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'], errors='coerce')

    # añadir timestamp de actualización
    df['last_update'] = datetime.now()

    return df

# =========================
# 4. GUARDAR RESULTADO
# =========================
def save_data(df, output_file):
    df.to_csv(output_file, index=False)
    print(f"Datos guardados en {output_file}")

# =========================
# 5. PIPELINE COMPLETO
# =========================
def run_pipeline():
    download_data(URL)
    df = clean_data()
    save_data(df, OUTPUT_FILE)
    print("Pipeline completado")

# =========================
# EJECUCIÓN
# =========================
if __name__ == "__main__":
    run_pipeline()