# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmePvMFsY6AOCmYYnWtx1FaP8lL-9YmC
"""

import pandas as pd
import requests
from datetime import datetime

# =========================
# 1. CONFIGURACIÓN
# =========================
API_BASE_URL = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"
RESOURCE_ID = "2ccf81f5-e913-41f1-85ab-3f8a6be74855" # Extraído de la URL anterior
OUTPUT_FILE = "data_cleaned.csv"

# =========================
# 2. DESCARGA DE DATOS (VIA API)
# =========================
def fetch_data_from_api(api_url, resource_id):
    print("Obteniendo datos de la API...")
    params = {'resource_id': resource_id, 'limit': 32000} # Se puede ajustar el límite o implementar paginación si hay muchos datos
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    response = requests.get(api_url, params=params, headers=headers)

    if response.status_code == 200:
        data = response.json()
        if data['success']:
            df = pd.DataFrame(data['result']['records'])
            print(f"Datos obtenidos de la API. Filas: {len(df)}")
            return df
        else:
            raise Exception(f"Error en la respuesta de la API: {data['error']}")
    else:
        raise Exception(f"Error al conectar con la API: {response.status_code} - {response.text[:200]}")

# =========================
# 3. LIMPIEZA DE DATOS
# =========================
def clean_data(df): # Ahora recibe el DataFrame directamente
    print("Limpiando datos...")
    print(df.columns) # Para ver las columnas en caso de futuros problemas

    df = df.drop_duplicates()

    # eliminar datos no válidos
    if "Nom_districte" in df.columns:
        df = df[df["Nom_districte"] != "Desconegut"]

    if "Codi_districte" in df.columns:
        df = df[df["Codi_districte"] != -1]

    # eliminar coordenadas vacías (se añadió una verificación de existencia de columnas)
    if "Latitud" in df.columns and "Longitud" in df.columns:
        df = df.dropna(subset=["Latitud", "Longitud"])
    else:
        print("Advertencia: Las columnas 'Latitud' o 'Longitud' no se encontraron en el DataFrame. Saltando la eliminación de nulos en estas columnas.")

    # convertir fecha
    if "Data" in df.columns:
        df["Data"] = pd.to_datetime(df["Data"], errors="coerce")

    # añadir timestamp de actualización
    df['last_update'] = datetime.now()

    return df

# =========================
# 4. GUARDAR RESULTADO
# =========================
def save_data(df, output_file):
    df.to_csv(output_file, index=False)
    print("Datos guardados")

# =========================
# 5. PIPELINE COMPLETO
# =========================
def run_pipeline():
    # Obtener datos usando la API
    df_raw = fetch_data_from_api(API_BASE_URL, RESOURCE_ID)
    df_cleaned = clean_data(df_raw) # Pasar el DataFrame a clean_data
    save_data(df_cleaned, OUTPUT_FILE)
    print("Pipeline completado")

# =========================
# EJECUCIÓN
# =========================
if __name__ == "__main__":
    run_pipeline()